# Generated by Django 3.2.7 on 2021-09-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
